### ISSUE TITLE
Duplicate documentation on readthedocs

### ISSUE THREAD

**Issue by berekuk** [graphql-python/graphql-core#104]
Significant parts of the [reference documentation](https://graphql-core-3.readthedocs.io/en/latest/modules/graphql.html) on readthedocs.io appear to be generated twice.

In the top-level reference it's the documentation for graphql.graphql and graphql.graphql_sync (first at the beginning and then at the end in "Top-Level Functions" section).

On some sub-package pages everything is repeated twice, e.g. on [graphql.error](https://graphql-core-3.readthedocs.io/en/latest/modules/error.html) page.

**Comment by Cito** [comment]
I have fixed this now, thanks for reporting. After upgrading Sphinx and adding some helper functionality to autodoc, the reference links should work much better now, too. You may need to reload the pages on Read the Docs in your browser.

Let me know if you still find any issues with the documentation.

**Comment by berekuk** [comment]
It looks correct now, thanks!
