### ISSUE TITLE
Multiple opearations fail together when response is none nullable 

### ISSUE THREAD

**Issue by pfreixes** [graphql-python/graphql-core#109]
# Input
I was providing the following GraphQL schema input to one of our services, which asked for executing a list of mutations as can bee seen in the following snippet

```
mutation M{
    first: foo(id: "1") {
        __typename
    }
    second: foo(id: "2") {
        __typename
    }
    third: foo(id: "3") {
        __typename
    }
}
```

# Expected Output
Once this input was provided and having one the mutations failing, in the example presented the one named `third`, I would expect the following output - `third` key is not present as part of the `data` keyword since we do not know the result of this operation.

```
{
    "data": {
        "first": {
            "__typename": "FooResult"
        },
        "second": {
            "__typename": "FooResult"
        }
    },
    "errors": [
        {
            "message": "An unknown error occurred.",
            "locations": [
                {
                    "line": 8,
                    "column": 5
                }
            ],
            "path": [
                "third"
            ]
        }
    ]
}
```
# Real output
But the real output that I got was this one

```
{
    "data": null,
    "errors": [
        {
            "message": "An unknown error occurred.",
            "locations": [
                {
                    "line": 8,
                    "column": 5
                }
            ],
            "path": [
                "third"
            ]
        }
    ]
}
```

Seems that when the schema is prescribing a none nullable output, GraphQL takes the path of raising an exception This seems to be the offender line [1].

The exception raised by [1] might make sense on a single GraphQL call, but when multiple calls are involved this prevents the user from knowing the result of other operations, though they might get the chance of being executed.

# Context
For the sake of providing context, I made the experiments by using GraphQL Core under the Ariadne [2] framework, the thought seems that Ariadne is not playing a critical role in the described behavior.

[1] https://github.com/graphql-python/graphql-core/blob/master/src/graphql/execution/execute.py#L703
[2] https://github.com/mirumee/ariadne

**Comment by Cito** [comment]
Thanks for the detailed report, @pfreixes.

In your example, it does not matter that these are mutations and take arguments, the same problem exists with simple queries.

You already mentioned the crucial thing here, namely that in your schema, "third" returns a non-null type. If it would return a nullable type, it would behave as you expected.

This behavior looks a bit astonishing and unhelpful, but I think it is according to the specs (see section [on errors and non-nullability](https://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability)), and the GraphQL.js reference implementation does the same [here](https://github.com/graphql/graphql-js/blob/f7061fdcf461a2e4b3c78077afaebefc2226c8e3/src/execution/execute.js#L772).
