### ISSUE TITLE
Default enum values ignored when parsing a schema

### ISSUE THREAD

**Issue by charmasaur** [graphql-python/graphql-core#111]
The following code:
```
import graphql
schema = graphql.build_ast_schema(graphql.parse("""
enum Enum {
  DEFAULT
}
input Input {
  enumField: Enum = DEFAULT
}"""))
print(schema.type_map['Input'].fields['enumField'].default_value)
```
produces `None`.

I guess I'm not really sure what it *should* be returning, but I think `"DEFAULT"` would be more appropriate than `None`.

**Comment by Cito** [comment]
Thanks for reporting. It boils down to this.

```python
>>> schema = graphql.build_ast_schema(graphql.parse("enum Enum { DEFAULT }"))
>>> print(schema.type_map['Enum'].values['DEFAULT'].value)
None
```

So, it looks like the internal values of the enum types created from SDL are set to `None`.

I agree they should better be the same as the names.

**Comment by charmasaur** [comment]
Thanks for the quick fix!
