### ISSUE TITLE
Return Type of complete_list_value

### ISSUE THREAD

**Issue by cancan101** [graphql-python/graphql-core#132]
Any reason that the return type of `complete_list_value` is `AwaitableOrValue[Any]` rather than `AwaitableOrValue[List[Any]]`:
https://github.com/graphql-python/graphql-core/blob/c6f73a8610ea01677992943dbde736f754bba296/src/graphql/execution/execute.py#L756-L763

For comparison, `execute_fields` returns `AwaitableOrValue[Dict[str, Any]]`:
https://github.com/graphql-python/graphql-core/blob/c6f73a8610ea01677992943dbde736f754bba296/src/graphql/execution/execute.py#L418-L424

**Comment by Cito** [comment]
Thank you, good catch! I've fixed it already.

**Comment by cancan101** [comment]
@Cito I think you also want to update the return types of `get_completed_results`, etc (the inner / helper functions).

**Comment by Cito** [comment]
Yes, but only one of them needed to be changed (5bfc3a099ed21969f3d0a24c6843ae7249a82e1e). Anything else I overlooked?

**Comment by cancan101** [comment]
That looks good.
