### ISSUE TITLE
How to unparse AST tree back to string?

### ISSUE THREAD

**Issue by undera** [graphql-python/graphql-core#134]
I have a need to do some manipulations on query text and it is conveniently done using AST tree. But then I need to represent the modified query back to string, for storage and logging.

I looked all over the source code and did not find a function to serialize AST back to string. Did I miss it?

If this functionality is out of scope for this repo - can you point me to the right place? Or suggest a strategy to implement such function?

**Comment by leszekhanusz** [comment]
You can use [print_ast](https://github.com/graphql-python/graphql-core/blob/ab209c49d6e350c311829ace6786fed51382166e/src/graphql/language/printer.py#L45)

**Comment by Cito** [comment]
In fact this function was missing in the reference documentation [here](https://graphql-core-3.readthedocs.io/en/latest/modules/language.html#printer).

**Comment by undera** [comment]
Awesome!

**Comment by leszekhanusz** [comment]
Also you might be interested in gql DSL module to [compose GraphQL queries dynamically from a schema](https://gql.readthedocs.io/en/v3.0.0a5/advanced/dsl_module.html#compose-queries-dynamically)
