### ISSUE TITLE
How to update `info.field_nodes[0].selection_set` ?

### ISSUE THREAD

**Issue by ldynia** [graphql-python/graphql-core#135]
# Context

I work with graphql in python ([graphql-core-3](https://graphql-core-3.readthedocs.io/en/latest/index.html)), and I have a GraphQL query that looks like this.

```graphql
query One {
  library(id: "library_1") {
    name
    book {
      title
      __typename
    }
    __typename
  }
}
```
When I investigate `info` object `info.field_nodes[0].selection_set.selections` I got selection set of `FieldNodes` that looks like that:

```
<class 'graphql.language.ast.SelectionSetNode'>
<class 'graphql.pyutils.frozen_list.FrozenList'> [FieldNode at 45:49, FieldNode at 54:95, FieldNode at 100:110]


# FieldNode at 45:49
name

# FieldNode at 54:95
book {
  title
  __typename
}

# FieldNode at 100:110
__typename
```

# Problem

In my second query set I added `results` field to wrap my data.

```graphql
query All {
  allLibrary {
    results {
      name
      book {
        title
        __typename
      }
      __typename
    }
    __typename
  }
}
```

Unfortunately, this causes a problem because query set is resolved from level of `allLibrary` not `library` as in the first example. The consequences of this structure is that `info.field_nodes[0].selection_set.selections` resolves fields incorrectly. Skiping, all the fields that I have interest in (`name` , `book`, `__typename`).

```python
<class 'graphql.language.ast.SelectionSetNode'>
<class 'graphql.pyutils.frozen_list.FrozenList'> [FieldNode at 14:147, FieldNode at 133:143] 

# FieldNode at 31:128
results {
  name
  book {
    title
    __typename
  }
  __typename
}

# FieldNode at 133:143
__typename
```

# Question 

How I can fix my `info.field_nodes[0].selection_set` so it fetches the `FieldNode` correctly ?

**Comment by Cito** [comment]
You just need to dig one level deeper, like `info.field_nodes[0].selection_set.selections[0].selection_set.selections`.

**Comment by ldynia** [comment]
Thank @Cito you saved my day :) 

By the way is there a simple way to loop down Field Nodes in python, to avoid hard coding indexes such `info.field_nodes[0].selection_set.selections[0].selection_set.selections` for below example?

```graphql
cities {
  name
  district {
    name
  }
  state {
    name
    country {
      name
      continent {
        name
      }
    }
  }
}
```

**Comment by Cito** [comment]
Sure, you could do something like this to get to the allLibrary.results in the first example:

```python
node = next(n for n in info.field_nodes if n.name.value == 'allLibrary')
nodes = node.selection_set.selections
node = next(n for n in nodes if n.name.value == 'results')
nodes = node.selection_set.selections
```

The "next" function is the Pythonic way to find the first field with the specified name.

The function metioned in #136 might be also interesting to you.

Btw, for "normal usage" you don't need to inspect the AST of the query. Maybe you're overcomplicating things?
