### ISSUE TITLE
Modify query programmatically

### ISSUE THREAD

**Issue by abitrolly** [graphql-python/graphql-core#149]
Sent here from https://github.com/graphql-python/gql/issues/272

There is a way in `gql` to construct queries programmatically with DSL module or by parsing a string into AST with `gql.gql()` and then using `print_ast` from `graphql` to get back the string.
```python
import gql

dg = gql.gql("""
    query getContinents {
      continents {
        code
        name
      }
    }
""")

from graphql import print_ast
print(print_ast(dg))
```

What is not clear is how to actually find nodes in AST and edit or expand them. For example, finding a parent of `node` in the query below (`continents`) and adding an attribute to it (`(code:"AF")`).
```graphql
query getContinents {
  continents {
    code
    name
  }
}
```
So that the query becomes.
```
    query getContinents {
      continents (code:"AF") {
        code
        name
      }
    }
```

I looked into the docs, but it doesn't actually explain.

* [ ] How to find AST node that needs modification?
* [ ] How to modify it (upsert attributes)?

The documentation container chapter about schemas https://graphql-core-3.readthedocs.io/en/latest/usage/extension.html?highlight=modify%20ast#extending-a-schema and as I am new to GraphQL I am not yet sure if schema and query are the same things.

# Feature requests

I am not sure [GraphQL.js](https://github.com/graphql/graphql-js) includes this too and not sure that fundamentally changes the way GraphQL works.

**Comment by Cito** [comment]
Hi @abitrolly. You *can* modify the query AST manually, but it is not something you would normally do.

Please check the [language](https://graphql-core-3.readthedocs.io/en/latest/modules/language.html) reference again, sorry it had been broken in *Read the Docs* lately.

Here is how you could solve your two tasks from above:

```python3
from graphql import (parse, print_ast,
                     ArgumentNode, NameNode, StringValueNode)

query = """
query getContinents {
  continents {
    code
    name
  }
}
"""

# Create AST from source

doc = parse(query)

# Find AST node that needs modification

field = doc.definitions[0].selection_set.selections[0]

# Modify it (add attributes)

field.arguments = [*field.arguments, ArgumentNode(
    name=NameNode(value='code'), value=StringValueNode(value='AF'))]

# Print modified AST

new_query = print_ast(doc)

print(new_query)
```

**Comment by abitrolly** [comment]
@Cito thanks. I still have troubles trying to figure out how to find out the position of element by name and then traverse up the hierarchy. In this particular example I need to find the element named 'code' and then add an attribute to its parent.

**Comment by Cito** [comment]
@abitrolly You can use a [Visitor](https://graphql-core-3.readthedocs.io/en/latest/modules/language.html#visitor) to traverse the AST. This will also give you access to the immediate parent and full list of ancestors of the current node.

Here is an example of a visitor that searches for a field node with the name 'code', and then adds another field node with the name 'newField' to its parent.

```python3
from graphql import FieldNode, NameNode, Visitor, parse, print_ast, visit
from graphql.pyutils import FrozenList

query = """
query getContinents {
  continents {
    code
    name
  }
}"""

doc = parse(query)

class ExampleVisitor(Visitor):

    def enter_name(self, node, key, parent, path, ancestors):
        if node.value == 'code' and parent.kind == 'field':
            parent = ancestors[-2]  # selection set
            parent.selections = FrozenList(
                (*parent.selections,
                 FieldNode(name=NameNode(value='newField'))))
            return True  # stop visiting

visitor = ExampleVisitor()
visit(doc, visitor)

new_query = print_ast(doc)

print(new_query)
```

Note: It is recommended to use a FrozenList instead of an ordinary list to make the nodes hashable.

**Comment by abitrolly** [comment]
I expected some kind of DOM/AST traverse methods, like `doc.findfirst('code').parent()` and then `.setattr('code', 'AF')`. That might work too.

So the code overwrites `.selections` attribute for the parent, and appends "FieldNode" to it, which would be the next sibling to `name` element. Need to test it and combine with attribute setter.

```
parent = ancestors[-2]  # selection set
```
Not `-1`, because there is an additional wrapping container like `selection set`?

Not sure why I need hashable nodes.

**Comment by Cito** [comment]
> I expected some kind of DOM/AST traverse methods, like `doc.findfirst('code').parent()` and then `.setattr('code', 'AF')`.

No, something like that doesn't exist in the API. As explained above, the AST is not really meant to be analyzed or modified by users of the API. The visit method is mainly used to implement the various validation rules.

> Not `-1`, because there is an additional wrapping container like `selection set`?

Exactly. The ancestor at -1 (parent) is just the list of field nodes (the selections attribute). You want its parent object which owns this list (selection set node).

> Not sure why I need hashable nodes.

It helps to cache nodes during execution. It might also help to detect AST changes and avoid re-validation if that is not the case.

**Comment by abitrolly** [comment]
I still need time to validate how it is going to work.

**Comment by Cito** [comment]
@abitrolly I'm currently going through the old tickets before creating the next release. Feel free to reopen or open a new issue if you have concrete questions.
