### ISSUE TITLE
[Sponsorship] Do you have any plans to accept sponsorship payments?

### ISSUE THREAD

**Issue by Ambro17** [graphql-python/graphql-core#151]
Basically title, i know the library has a single mantainer (@cito) and as far as i know it's not paid to do this so features may take longer to arrive from js implementation.
The company i work for is analyzing different sponsorship options and i think this library is a great candidate as it's really core but is not valued proportionally in its funding

**Comment by Cito** [comment]
That's right, I'm currently maintaining this library and keeping it in line with the JS library as a side/hobby project, as time permits. It would definitely help to make this more sustainable if I could get some sponsoring, so I will think about that and maybe register this with GitHub sponsors. Will leave this open as a reminder :)

**Comment by Ambro17** [comment]
Hello! Have you had time to analyze it?

**Comment by Cito** [comment]
@Ambro17 yes, currently waiting for Github to approve. This may take some days.

**Comment by Cito** [comment]
Sponsoring the development of this project is now possible via the :heart: "Sponsor" button on the right side of the [project page](https://github.com/graphql-python/graphql-core).

Thanks in advance for all who want to motivate me that way and help building a culture of sustainable open source development.

**Comment by Cito** [comment]
Thank you @Ambro17 and @jkimbo for being my first sponsors! It's always nice to get such positive feedback.
