### ISSUE TITLE
How to use user directives?

### ISSUE THREAD

**Issue by bronte2k7** [graphql-python/graphql-core#162]
Hi

Most classes have good descriptions and examples. But GraphQLDirective doesn't include any examples. Therefore, there was a difficulty in how to use it?

```python

test = GraphQLDirective(name='test', locations=[DirectiveLocation.QUERY])
schema = GraphQLSchema(query=query, types=[demo_type], directives=[test])
```
How to apply test directive to query type?

**Comment by Cito** [comment]
Hi @bronte2k7

> How to apply test directive to query type?

This is deliberately not supported by GraphQL.js (and thus also not by GraphQL-core).

The reasons are explained best [in this comment](https://github.com/graphql/graphql-js/issues/1343#issuecomment-459156658).

**Comment by bronte2k7** [comment]
> Hi @bronte2k7
> 
> > How to apply test directive to query type?
> 
> This is deliberately not supported by GraphQL.js (and thus also not by GraphQL-core).
> 
> The reasons are explained best [in this comment](https://github.com/graphql/graphql-js/issues/1343#issuecomment-459156658).

Thanks for your reply. Сomment helped me)))
