### ISSUE TITLE
Include name in representation of named nodes

### ISSUE THREAD

**Issue by LinuxIsCool** [graphql-python/graphql-core#198]
I'm parsing schema's to build datasets of available queries. Having a __repr__ on nodes that displays attribute information would be very useful. I'm looking at my code from 2 years ago which had this functionality. Running the same code today renders non-useful __repr__ of nodes. 

Notebook state that I ran 2 years ago:
![image](https://github.com/graphql-python/graphql-core/assets/31582215/12a53950-4ab0-4b70-ae01-e00a5ae59e97)

Notebook state ran today:
![image](https://github.com/graphql-python/graphql-core/assets/31582215/19e35f81-373c-4e56-949c-d4f8a70da77b)

You can see how the __repr__ displaying the value of the name is very useful.

**Comment by Cito** [comment]
Thanks for the suggestion. This is now implemented in 3.3.0a3.
