### ISSUE TITLE
subscribe breaking change in graphql version 3.3.0a3

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/graphql-core#202]
It seems we don't need to use `await` anymore with the `subscribe` method since the [latest 3.3.0a3 pre-release](https://github.com/graphql-python/graphql-core/releases/tag/v3.3.0a3).

This causes current [gql tests to fail](https://github.com/graphql-python/gql/issues/416) with either:

- `TypeError: object async_generator can't be used in 'await' expression`
- `TypeError: object ExecutionResult can't be used in 'await' expression`

That new interface seems cleaner but could you please maybe indicate that breaking change in the release notes?

Thanks,

**Comment by Cito** [comment]
Right, this is a breanking change that is now mentioned in the release notes. It mirrors a [similar](https://github.com/graphql/graphql-js/pull/3620) change in GraphQL.js.
