### ISSUE TITLE
[Question] How to map operation variables to their uses?

### ISSUE THREAD

**Issue by nrbnlulu** [graphql-python/graphql-core#204]
I need to map each field in an operation variable to a list of fields where it is being used as an argument is that doable? 

The use case is that I need to cache fields based on what argument they were provided. And since queries can have different variable names I can't use that name for caching.

**Comment by erikwrede** [comment]
You'll need to analyze the AST for that. You'll get the AST after parsing using `parse(document)`. Variables are always passed to arguments or children of arguments, so it's best to have a look at all `ArgumentNode`s using BFS/DFS:
https://github.com/graphql-python/graphql-core/blob/0c93b8452eed38d4f800c7e71cf6f3f3758cd1c6/src/graphql/language/ast.py#L520-L524

The possible inputs to ArgumentNodes are the subclasses of `ValueNode`. If you just want to look for Variables, not constants, do another DFS search inside each `ArgumentNode`, expanding all the `ListValueNode`s and `ObjectValueNode`s.

You can also write a custom visitor to save the effort of manually performing the search and call it using the visit function: https://github.com/graphql-python/graphql-core/blob/main/src/graphql/language/visitor.py

Hope that helps, LMK if you have any questions. Am curious about the use case so please feel free to share more (maybe not in this issue though, so we don't add too much noise)🙂

**Comment by nrbnlulu** [comment]
Since I parse every operation down to field level I added an argument evaluator that will map
variable uses to field definition, looks like this:
```py
def _evaluate_variable_uses(
    type_info: OperationTypeInfo,
    field: QtGqlFieldDefinition,
    arguments: tuple[gql_lang.ArgumentNode, ...],
) -> list[QtGqlVariableUse]:
    ret: list[QtGqlVariableUse] = []
    for arg in arguments:
        index = field.index_for_argument(arg.name.value)
        var_name = arg.value.name.value  # type: ignore[attr-defined]
        for variable in type_info.variables:
            if var_name == variable.name:
                ret.append(
                    QtGqlVariableUse(argument=(index, field.arguments[index]), variable=variable),
                )
    assert len(ret) == len(arguments), "could not find all variable uses"
    return ret


def _evaluate_variable_node_type(
    type_info: SchemaTypeInfo,
    node: graphql.TypeNode,
) -> QtGqlTypeABC:
    if nonnull := is_nonnull_node(node):
        return evaluate_graphql_type(
            type_info,
            graphql.type.GraphQLNonNull(
                type_info.schema_definition.get_type(nonnull.type.name.value),  # type: ignore
            ),
        )

    if named_type := is_named_type_node(node):
        gql_concrete = type_info.schema_definition.get_type(named_type.name.value)
        assert gql_concrete
        return evaluate_graphql_type(type_info, gql_concrete)
    raise NotImplementedError(node, "Type is not supported as a variable ATM")
```

Then fields that has arguments are stored in a map that is that looks like this
```cpp
std::map<std::tuple<(argument types)>, (value)>
```
And when an operation is deserialized the value is set on that field based on the operation argument that
I already determined what they should be.
