### ISSUE TITLE
Pregenerate and Caching GraphqlSchema with Pickle

### ISSUE THREAD

**Issue by vt-rc** [graphql-python/graphql-core#222]
I am running graphene-django on serverless
I am posting here because Schema loading is in GraphqlSchema.

often time when there is cold start and the cold start is very slow because the schema loading is very slow, 1xx+ms for a fairly small schema. For larger service the schema load time can be over 3xx-4xx+ms

(please don't tell me to stop running serverless, thx)

I am trying to pregenerate and cache the Schema for production environment, 

I tried to pickle the schema because I saw #173  , but it isn't working. I am getting the error
`
Can't pickle local object 'TypeMap.create_objecttype.<locals>.interfaces
`

Or are there other way to speed up start time? Maybe write it in another language as extension?

**Comment by Cito** [comment]
Pickling schemas should work and is tested as part of the test suite since GraphQL-core 3.3.0a2. Probably you're using an older version of GraphQL-core.

**Comment by vt-rc** [comment]
I just upgraded and now I am getting this error

`    pickle.dump(self.graphql_schema, f)
`

`_pickle.PicklingError: Can't pickle <XxxxxNodeConnection meta=<ConnectionOptions name='XxxxxNodeConnection'>>: attribute lookup XxxxxNodeConnection on graphene.types.objecttype failed`

**Comment by Cito** [comment]
Looks like this happens because the Graphene schema wrapper or some types created by it cannot be pickled. Unfortunately this cannot be solved here. The [Graphene](https://github.com/graphql-python/graphene) project would be the right place to ask for help.

**Comment by vt-rc** [comment]
Thank you so much for your prompt reply. You are wonderful!!!
