### ISSUE TITLE
Weakref unsupported in AST

### ISSUE THREAD

**Issue by astronouth7303** [graphql-python/graphql-core#81]
`graphql.language.ast` makes extensive use of `__slots__` but `__weakref__` is given, breaking the `weakref` module.

* [Python Documentation about `__slots__`](https://docs.python.org/3/reference/datamodel.html#slots)

The use of `__slots__` without `__weakref__` makes it very hard to track data about AST nodes in a non-leaky way.

**Comment by astronouth7303** [comment]
My use case: My library does analysis of graphql queries, including figuring out the schema type of each node (for later directive finding).

The slots & no weakref situation means that I can't attach data directly to nodes, I'll keep the nodes around if I keep them in a dictionary, and I'll leak data if I use the object IDs.

**Comment by Cito** [comment]
Thanks for the feedback, @astronouth7303. Does it solve your problem when we add `"__weakref__"` to the `__slots__` attribute of `Node`? What be the disadvantages of this change? Just a slightly higher memory consumption overall because of the additional slot, right?

**Comment by astronouth7303** [comment]
Yup, that'll fix it up nice.

I think there _might_ be a _slight_ memory increase, something like an extra pointer per instance. I'm not intimately familiar with what `__slots__` does under the hood, though, so the above is speculation. I believe the usual rules of attributes still exist (namely that the attribute doesn't exist until it's assigned to, which in this case I'm pretty sure happens on first weakref use).
