### ISSUE TITLE
Add type annotations for all definitions

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphql-core#89]
We should add type annotations for all definitions except those in tests, and enforce this with a `mypy.ini` configuration like this:

```
[mypy]
python_version = 3.8
...
disallow_untyped_defs = True

[mypy-tests.*]
disallow_untyped_defs = False
```

**Comment by KingDarBoja** [comment]
Could you provide an example regarding type annotations for definitions that are missing? Cheers!

**Comment by Cito** [comment]
@KingDarBoja When you set `disallow_untyped_defs = True`, mypy will list all the missing definitions, like missing return type of a `__str__` method, and missing type annotations for internal functions.

**Comment by Cito** [comment]
I have now added all the missing definitions, except for a few modules where it makes no sense or where I'm waiting for #99.
