### ISSUE TITLE
Generate schema with directive at field

### ISSUE THREAD

**Issue by hspedro** [graphql-python/graphql-core#90]
# Feature requests

Hi all, I'm trying to generate a schema that has a directive at a field:
```graphql
directive @hasPermissions(permissions: [String]) on OBJECT | FIELD_DEFINITION

type MyType {
  field1: Boolean @hasPermissions(permissions: ['permission1', 'permission2'])
}

type Query {
  myType: MyType
}
```

However, I did not found a way to generate this using the library. For instance, I tried defining the `directives` attribute from `GraphQLField.ast_node` but `print_schema` did not generated field with the directive:
```python
from graphql.language import (
    FieldDefinitionNode, DirectiveLocation, DirectiveNode, ArgumentNode
)
from graphql.type import (
    GraphQLArgument,
    GraphQLBoolean,
    GraphQLDirective,
    GraphQLField,
    GraphQLList,
    GraphQLObjectType,
    GraphQLSchema,
    GraphQLString,
)
from graphql.utilities import print_schema

if __name__ == "__main__":
    MyType = GraphQLObjectType(
        "MyType",
        lambda: {
            "field1": GraphQLField(
                GraphQLBoolean,
                ast_node=FieldDefinitionNode(
                    directives=[DirectiveNode(
                        name="hasPermissions",
                        arguments=[
                            ArgumentNode(
                                name="permissions",
                                value=["permission1", "permission2"]
                            )
                        ]
                    )]
                )
            ),
        },
    )

    MyTypeQuery = GraphQLObjectType(
        "Query",
        {
            "myType": GraphQLField(MyType),
        },
    )
    schema = GraphQLSchema(
        directives=[GraphQLDirective(
            name="hasPermissions",
            locations=[
                DirectiveLocation.OBJECT,
                DirectiveLocation.FIELD_DEFINITION
            ],
            args={
                "permissions": GraphQLArgument(GraphQLList(GraphQLString)),
            },
        )],
        query=MyTypeQuery,
    )
    print(print_schema(schema))
```

Output:
```graphql
directive @hasPermissions(permissions: [String]) on OBJECT | FIELD_DEFINITION

type Query {
  myType: MyType
}

type MyType {
  field1: Boolean
}
```

Is there any way to generate a schema with directive at the field declaration? If not, I can contribute on that.

**Comment by hspedro** [comment]
As I was debugging, I saw that `print_field` from `print_schema.py` only writes the directive for `@deprecated`. Could it be the case of adding something to recursively parse `ast_node.directives` and add to `print_fields`? https://github.com/graphql-python/graphql-core/blob/master/src/graphql/utilities/print_schema.py#L197

**Comment by Cito** [comment]
Currently, you can add custom directives only via SDL, like this:

```python
schema = build_schema("""
directive @hasPermissions(permissions: [String]) on OBJECT | FIELD_DEFINITION

type MyType {
  field1: Boolean @hasPermissions(permissions: ["permission1", "permission2"])
}

type Query {
  myType: MyType
}
""")
```

Arguably, this is also the only case where such directives are needed. On your hand-made object types, you can simply use a `hasPermissions` function in your resolvers instead of using directives.

There are long discussions about this in JavaScript land e.g. [here](https://github.com/graphql/graphql-js/issues/1262) and [here](https://github.com/graphql/graphql-js/issues/1343).

The goal of graphql-core is to be a 1:1 port of GraphQL.js. If you have good reasons to add a feature, you can advocate this to the GraphQL.js folks which have great expertise and experience. If they agree it makes sense, it will be eventually implemented there and then ported over here.
