### ISSUE TITLE
Allow caching of parsing requests

### ISSUE THREAD

**Issue by jnak** [graphql-python/graphql-core#94]
Hi,

Currently there is no way to cache the parsing of the queries because `graphql_impl` only [accepts queries as strings](https://github.com/graphql-python/graphql-core/blob/6687b168b82e6c1722bb9748430f8785cabe46f5/src/graphql/graphql.py#L152). While we probably don't want to bring back the concept of `backend` from GraphQL V2, we could simply extend `graphql_impl` to take a query string or a parsed document so callers have a chance to cache the parsing (see https://github.com/graphql-python/graphql-server-core/issues/43). Additionally, it will allow callers to do finer-grained error handling in case the parsing fail. For example, we probably don't want to alert when a client sends a malformed query. 

Cheers,
J

**Comment by jnak** [comment]
Just saw [your reply](https://github.com/graphql-python/graphql-server-core/issues/43#issuecomment-635493086) in the other thread. Makes a lot of sense. I didn't realize `execute` was considered a public function. Thanks!

**Comment by Cito** [comment]
Yes, the `execute()` function and the functions for parsing and validating queries are all public and part of the official API.
