### ISSUE TITLE
Implement specifiedBy directive merged into graphql-js

### ISSUE THREAD

**Issue by Ambro17** [graphql-python/graphql-core#95]
As per issue [#649](https://github.com/graphql/graphql-spec/pull/649) and the [merged pr](https://github.com/graphql/graphql-js/pull/2276) the reference implementation now includes a new directive.
I understand that this lib is intended as a 1 to 1 port to graphql-js so perhaps we should consider including it.
If not possible, we should document the divergence

**Comment by Cito** [comment]
This has already been included in 9228af4dfba79d14bb06da0666a2ab66f7fd7b95 and will be available soon with the next release.

**Comment by Ambro17** [comment]
Thank you!
