### ISSUE TITLE
Change special return value for REMOVE

### ISSUE THREAD

**Issue by LWprogramming** [graphql-python/graphql-core#96]
The `visitor.py` file sets the special value [`REMOVE` to `Ellipsis`](https://github.com/graphql-python/graphql-core/blob/master/src/graphql/language/visitor.py#L34). However, this causes trouble with type-hinting functions that return REMOVE. Could we create a separate value rather than using `Ellipsis`? See the [issues linked here](https://github.com/kensho-technologies/graphql-compiler/pull/834#discussion_r435360797), where the consensus is in favor of not using the `Ellipsis` constant. Thank you!

**Comment by Cito** [comment]
Maybe we should create an enum `VisitorAction` containing these four special values, and set `REMOVE` to `VisitorAction.REMOVE` etc. Then adding type hints would be even easier. For backward compatibility, the visitor could still recognize the other special values like `Ellipsis`.

Would that solve the problem?

**Comment by LWprogramming** [comment]
That would work! Arguably it would work even better because we wouldn't need to update the type-hint every time we have a visitor function return a different special value.

**Comment by Cito** [comment]
I have implemented this in the master branch now.
