### ISSUE TITLE
Disable suggestion "Remove Did you mean..."

### ISSUE THREAD

**Issue by ckristhoff** [graphql-python/graphql-core#97]
Hi
When you post an query with syntax errors graphql/graphene makes suggestions to you. By example, sending "i", it suggest "ID".
```graphql
query{
  users{
        i
  }
}
```
```
{
  "errors": [
    {
      "message": "Cannot query field \"i\" on type \"User\". Did you mean \"id\"?",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ]
    }
  ]
}
```

Can suggestions be disabled?

More info: 
Syntax analysis who add suggestions is executed before the middlewares.
Apparently suggestions are made by [ScalarLeafsRule](https://github.com/graphql-python/graphql-core/blob/master/src/graphql/validation/rules/scalar_leafs.py#L9) class.

**Comment by Cito** [comment]
There's no official way to switch them off. You could of course monkey patch the function that creates them (to remove them generally) or use custom validation rules (replacing ScalarLeafsRule) or filter them out. But why would you want to do that?

**Comment by ckristhoff** [comment]
Hello @Cito 
thanks for your answer. My customer requires disable it and the introspection query because they watch this like as security vulnerability. I already disable the introspection query using a middleware.

**Comment by Cito** [comment]
Ok, if you want to keep it closed and also disable introspection it makes a little more sense. I suggest you simply set `graphql.pyutils.did_you_mean.MAX_LENGTH = 0`. I just commited a small change ffdf1b3702505cbcfd9fca7d6bde191e7d3f5e47 that makes this work a bit better.

You can also ask over at [https://github.com/graphql/graphql-js/issues](graphql-js) if they want to add some functionality to support your use case. From there it would be ported back here.

**Comment by ckristhoff** [comment]
@Cito you'r awesome
`graphql.pyutils.did_you_mean.MAX_LENGTH` can be setted from django? or directly from graphql-python source code?.

**Comment by Cito** [comment]
Sorry, since the function has the same name as the module, you need to set it like this:
```python
from graphql.pyutils import did_you_mean
did_you_mean.__globals__['MAX_LENGTH'] = 0
```
This must be run once in your Python interpreter before you start the the GraphQL server. In Django you should probably put this in the `__init__.py` file of your app.

**Comment by ckristhoff** [comment]
It works really well in graphql-core 3. Any suggestion for 2.3.2 (legacy) version?
2.3.2 version doesn't have did_you_mean module.  😕

**Comment by ckristhoff** [comment]
Possible solution for legacy 2.3.2 version.

Ok, in legacy version source code I found the `FieldsOnCorrectType` validator rule. It crafts the error message with the suggestion. So my current solution is:

```python
from graphql.validation import rules
def get_empty_suggested_field_names(schema, graphql_type, field_name):
    return []
def get_empty_suggested_type_names(schema, output_type, field_name):
    return []
rules.fields_on_correct_type.get_suggested_field_names = get_empty_suggested_field_names
rules.fields_on_correct_type.get_suggested_type_names = get_empty_suggested_type_names
```
this solution replaces the functions which generate the suggestions. In Django, this can placed in settings file.

What do you think about this solution? 

More info: Use the same process to override the `_unknown_arg_message` and `_unknown_directive_arg_message` functions on `KnownArgumentNames` validator rule.

```python
def _unknown_arg_message(arg_name, field_name, type, suggested_args):
    message = 'Unknown argument "{}" on field "{}" of type "{}".'.format(
        arg_name, field_name, type
    )
    return message
def _unknown_directive_arg_message(arg_name, directive_name, suggested_args):
    message = 'Unknown argument "{}" on directive "@{}".'.format(
        arg_name, directive_name
    )
    return message
rules.known_argument_names._unknown_arg_message = _unknown_arg_message
rules.known_argument_names._unknown_directive_arg_message = _unknown_directive_arg_message
```

**Comment by Cito** [comment]
Yes, it's more difficult in the legacy version because it does not have one dedicated function to produce these message. The simplest way here is to monkey-patch the individual functions for creating the messages; you need to do that with `fields_on_correct_type._undefined_field_message`,  `known_type_names._unknown_type_message`, `known_argument_names._unknown_arg_message` and `known_argument_names._unknown_directive_arg_message`. I'd normally not recommend patching such private internal functions, but the legacy version is not under development any more and I do not expect these internals to change even if there are bugfix releases.

GraphQL-core 3 has two more rules with suggestions, but they are all using the same `did_you_mean` function, so it suffices to change its `MAX_LENGTH` constant. Of course there is no guarantee that this will always work in future versions, since it is not part of the official API. As already mentioned, changes in the official API should be requested in GraphQL.js.

**Comment by ckristhoff** [comment]
Thank you so much @Cito you are awesome! 🥇

**Comment by Cito** [comment]
For the record: as of graphql-core 3.3.0a13, this can be done without monkey-patching.

The ported upstream feature (graphql/graphql-js#4214) adds a `hide_suggestions` flag on `graphql()`, `graphql_sync()`, `execute()`, and `validate()` that suppresses the "Did you mean …?" hints:

```py
result = graphql_sync(schema, "{ users { i } }", hide_suggestions=True)
# Cannot query field 'i' on type 'User'.   (no "Did you mean 'id'?")
```

It applies to both validation errors and input-value coercion messages.
