### ISSUE TITLE
Make use of TypedDict

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphql-core#99]
We could make use of [TypedDict](https://www.python.org/dev/peps/pep-0589/) in several places, for instance as return value of  `to_kwargs` and `introspection_from_schema`.

Unfortunately, this needs Python 3.8, but we are currently supporting Python 3.6. However, it should be possible to add `typing_extensions` as additional dependency for Python 3.6 and 3.7 to support TypedDict for these Python versions as well.

**Comment by KingDarBoja** [comment]
Started to use `TypedDict` on **graphql-server-core**, those are awesome to work with and the `typing_extensions` does the job to bring backward compatibility to Python 3.6 and 3.7. Only thing that you must be aware is that you must provide all values to any TypeDict declaration as those doesn't support default values on class definition as far as I know.

**Comment by Cito** [comment]
This has now been implemented for `introspection_from_schema` in 24506f31ed1dbd104d0f5481965d0e0814f127f1.

Still needs to be implemented for `to_kwargs`.

**Comment by Cito** [comment]
This is now also implemented for `to_kwargs`, so we can close this issue.
